language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test
    - stage: build
      if: tag IS present
      script: yarn release
    - stage: deploy
      if: tag IS present
      script:
        - bash scripts/deploy-surge.sh
        - bash scripts/deploy-pages.sh
